/**
 * Русские тексты для ошибок, которые написаны по-английски в глубине кода.
 * Подменяются при отправке ответа: сам код и его тесты остаются как были.
 */
const RU = new Map(Object.entries({
  "An identical request is still being processed": "Такой же запрос ещё выполняется",
  "Authentication required": "Нужно войти в систему",
  "Bad request": "Некорректный запрос",
  "Calendar route not found": "Такого раздела календаря нет",
  "Channel not found": "Канал не найден",
  "Checklist item not found": "Пункт списка не найден",
  "Collaborator not found": "Участник задачи не найден",
  "Conversation member not found": "Участник беседы не найден",
  "Conversation must keep at least one owner": "В беседе должен остаться хотя бы один владелец",
  "Conversation not found": "Беседа не найдена",
  "Conversation participant must belong to the workspace": "Участник беседы должен быть из этой компании",
  "Current password is wrong": "Текущий пароль указан неверно",
  "Dependency not found": "Зависимость не найдена",
  "Direct conversation membership is immutable": "Состав личной переписки менять нельзя",
  "File is empty": "Файл пустой",
  "File not found": "Файл не найден",
  "Game route not found": "Такого раздела игр нет",
  "Games require a database deployment": "Игры работают только с базой данных",
  "Idempotency-Key is too long": "Ключ повтора запроса слишком длинный",
  "Integration route not found": "Такого раздела интеграций нет",
  "Invalid JSON": "Не удалось разобрать запрос",
  "Invalid date": "Не удалось разобрать дату",
  "Invalid push subscription": "Некорректная подписка на уведомления",
  "Invalid voice duration": "Недопустимая длительность голосового сообщения",
  "Invitation has expired": "Срок приглашения истёк",
  "Invitation is not available": "Приглашение недоступно",
  "Label route not found": "Такого раздела меток нет",
  "Mark route not found": "Такого раздела пометок нет",
  "Message not found": "Сообщение не найдено",
  "Message reference is not available in this conversation": "Это сообщение недоступно в этой беседе",
  "Method not allowed": "Такой способ запроса не поддерживается",
  "No credentials for this account": "У этой учётной записи нет пароля",
  "Not found": "Не найдено",
  "Notification not found": "Уведомление не найдено",
  "Only channel managers may publish in this announcement channel": "В канале объявлений пишут только его руководители",
  "Org route not found": "Такого раздела оргструктуры нет",
  "Outbound integrations require a PostgreSQL deployment": "Исходящие интеграции работают только с базой данных",
  "Password recovery requires a database deployment": "Восстановление пароля работает только с базой данных",
  "People route not found": "Такого раздела людей нет",
  "Person not found": "Человек не найден",
  "Personal marks require a database deployment": "Личные пометки работают только с базой данных",
  "Personal route not found": "Такого личного раздела нет",
  "Position must be a whole number": "Позиция должна быть целым числом",
  "Preview is not available for this file type": "Для этого типа файла предпросмотра нет",
  "Proposal is no longer pending": "По этому предложению решение уже принято",
  "Query is too long": "Запрос слишком длинный",
  "Reminder route not found": "Такого раздела напоминаний нет",
  "Reminders require a database deployment": "Напоминания работают только с базой данных",
  "Request too large": "Запрос слишком большой",
  "Session not found": "Вход не найден",
  "Target conversation not found": "Беседа назначения не найдена",
  "Task not found": "Задача не найдена",
  "Task participant must belong to the workspace": "Участник задачи должен быть из этой компании",
  "Task source message not found": "Исходное сообщение задачи не найдено",
  "That message is not in this conversation": "Этого сообщения нет в этой беседе",
  "The organisational chart requires a PostgreSQL deployment": "Оргструктура работает только с базой данных",
  "This Idempotency-Key was already used for a different request": "Этот ключ повтора уже использован для другого запроса",
  "This conversation still has an owner": "У этой беседы уже есть владелец",
  "This email already has an account; sign in before joining another workspace": "У этого адреса уже есть учётная запись: войдите, прежде чем присоединяться к другой компании",
  "This recovery link has expired": "Срок ссылки для восстановления истёк",
  "This recovery link is not valid": "Ссылка для восстановления недействительна",
  "Too many attempts. Please wait before trying again.": "Слишком много попыток. Подождите и попробуйте снова",
  "Unknown dependency kind": "Неизвестный вид зависимости",
  "Unsupported evidence type": "Такой тип доказательства не поддерживается",
  "Webhook payload too large": "Данные вебхука слишком большие",
  "You do not manage this unit": "Вы не управляете этим подразделением",
  "Conversation management permission required": "Нужны права на управление беседой",
  "Invalid conversation role": "Недопустимая роль в беседе",
  "Unsupported conversation kind": "Такой вид беседы не поддерживается",
  "Direct conversation requires exactly two users": "Личная переписка — ровно двое",
  "At least one userId is required": "Нужно указать хотя бы одного человека",
  "Malformed cursor": "Некорректная позиция в списке",
  "Malformed message id": "Некорректный номер сообщения",
  "Invalid mutedUntil": "Некорректное время заглушения",
  "Invalid presence state": "Такого статуса присутствия нет",
  "Unsupported conversation role": "Недопустимая роль в беседе"
}));

export const russianMessage = (message) => RU.get(message) ?? message;
