/**
 * Русские тексты для ошибок, которые написаны по-английски в глубине кода.
 * Подменяются при отправке ответа: сам код и его тесты остаются как были.
 */
const RU = new Map(Object.entries({
  "A guest cannot carry a commitment": "Гость не может быть исполнителем задачи",
  "Reassigning requires a reason": "Для передачи задачи нужна причина",
  "Rescheduling requires a reason": "Для переноса срока нужна причина",
  "Evidence URL is not a valid address": "Ссылка в доказательстве указана неверно",
  "Evidence URL must be http or https": "Ссылка в доказательстве должна начинаться с http:// или https://",
  "Evidence metric must start with a number": "Показатель должен начинаться с числа",
  "Evidence message is not available": "Сообщение из доказательства недоступно",
  "Those people are not workspace staff": "Эти люди не сотрудники компании",
  "Nobody to invite": "Некого приглашать",
  "A guest cannot change conversation roles": "Гость не может менять роли в беседе",
  "A direct conversation cannot be left; archive it instead": "Из личной переписки выйти нельзя — отправьте её в архив",
  "Forwarded message content is immutable": "Пересланное сообщение изменить нельзя",
  "Only text messages can be edited": "Править можно только текстовые сообщения",
  "Endpoint label is required": "Укажите название подписки",
  "A display name is required": "Укажите имя",
  "Topics must be an array of patterns": "Темы должны быть списком",
  "An identical request is still being processed": "Такой же запрос ещё выполняется",
  "Authentication required": "Нужно войти в систему",
  "Bad request": "Некорректный запрос",
  "Calendar route not found": "Такого раздела календаря нет",
  "Channel not found": "Канал не найден",
  "Checklist item not found": "Пункт списка не найден",
  "Collaborator not found": "Участник задачи не найден",
  "Conversation member not found": "Участник беседы не найден",
  "Conversation must keep at least one owner": "В беседе должен остаться хотя бы один владелец",
  "Conversation not found": "Беседа не найдена",
  "Conversation participant must belong to the workspace": "Участник беседы должен быть из этой компании",
  "Current password is wrong": "Текущий пароль указан неверно",
  "Dependency not found": "Зависимость не найдена",
  "Direct conversation membership is immutable": "Состав личной переписки менять нельзя",
  "File is empty": "Файл пустой",
  "File not found": "Файл не найден",
  "Game route not found": "Такого раздела игр нет",
  "Games require a database deployment": "Игры работают только с базой данных",
  "Idempotency-Key is too long": "Ключ повтора запроса слишком длинный",
  "Integration route not found": "Такого раздела интеграций нет",
  "Invalid JSON": "Не удалось разобрать запрос",
  "Invalid date": "Не удалось разобрать дату",
  "Invalid push subscription": "Некорректная подписка на уведомления",
  "Invalid voice duration": "Недопустимая длительность голосового сообщения",
  "Invitation has expired": "Срок приглашения истёк",
  "Invitation is not available": "Приглашение недоступно",
  "Label route not found": "Такого раздела меток нет",
  "Mark route not found": "Такого раздела пометок нет",
  "Message not found": "Сообщение не найдено",
  "Message reference is not available in this conversation": "Это сообщение недоступно в этой беседе",
  "Method not allowed": "Такой способ запроса не поддерживается",
  "No credentials for this account": "У этой учётной записи нет пароля",
  "Not found": "Не найдено",
  "Notification not found": "Уведомление не найдено",
  "Only channel managers may publish in this announcement channel": "В канале объявлений пишут только его руководители",
  "Org route not found": "Такого раздела оргструктуры нет",
  "Outbound integrations require a PostgreSQL deployment": "Исходящие интеграции работают только с базой данных",
  "Password recovery requires a database deployment": "Восстановление пароля работает только с базой данных",
  "People route not found": "Такого раздела людей нет",
  "Person not found": "Человек не найден",
  "Personal marks require a database deployment": "Личные пометки работают только с базой данных",
  "Personal route not found": "Такого личного раздела нет",
  "Position must be a whole number": "Позиция должна быть целым числом",
  "Preview is not available for this file type": "Для этого типа файла предпросмотра нет",
  "Proposal is no longer pending": "По этому предложению решение уже принято",
  "Query is too long": "Запрос слишком длинный",
  "Reminder route not found": "Такого раздела напоминаний нет",
  "Reminders require a database deployment": "Напоминания работают только с базой данных",
  "Request too large": "Запрос слишком большой",
  "Session not found": "Вход не найден",
  "Target conversation not found": "Беседа назначения не найдена",
  "Task not found": "Задача не найдена",
  "Task participant must belong to the workspace": "Участник задачи должен быть из этой компании",
  "Task source message not found": "Исходное сообщение задачи не найдено",
  "That message is not in this conversation": "Этого сообщения нет в этой беседе",
  "The organisational chart requires a PostgreSQL deployment": "Оргструктура работает только с базой данных",
  "This Idempotency-Key was already used for a different request": "Этот ключ повтора уже использован для другого запроса",
  "This conversation still has an owner": "У этой беседы уже есть владелец",
  "This email already has an account; sign in before joining another workspace": "У этого адреса уже есть учётная запись: войдите, прежде чем присоединяться к другой компании",
  "This recovery link has expired": "Срок ссылки для восстановления истёк",
  "This recovery link is not valid": "Ссылка для восстановления недействительна",
  "Too many attempts. Please wait before trying again.": "Слишком много попыток. Подождите и попробуйте снова",
  "Unknown dependency kind": "Неизвестный вид зависимости",
  "Unsupported evidence type": "Такой тип доказательства не поддерживается",
  "Webhook payload too large": "Данные вебхука слишком большие",
  "You do not manage this unit": "Вы не управляете этим подразделением",
  "Conversation management permission required": "Нужны права на управление беседой",
  "Invalid conversation role": "Недопустимая роль в беседе",
  "Unsupported conversation kind": "Такой вид беседы не поддерживается",
  "Direct conversation requires exactly two users": "Личная переписка — ровно двое",
  "At least one userId is required": "Нужно указать хотя бы одного человека",
  "Malformed cursor": "Некорректная позиция в списке",
  "Malformed message id": "Некорректный номер сообщения",
  "Invalid mutedUntil": "Некорректное время заглушения",
  "Invalid presence state": "Такого статуса присутствия нет",
  "Unsupported conversation role": "Недопустимая роль в беседе",
  "API route not found": "Такого адреса нет",
  "A value has the wrong format": "Значение указано в неверном формате",
  "A value failed a validation rule": "Значение не подходит под правила",
  "A record with these values already exists": "Такая запись уже есть",
  "A referenced record does not exist": "Связанной записи не существует",
  "The text contains characters the database cannot store": "В тексте есть символы, которые нельзя сохранить",
  "The number is out of range": "Число вне допустимого диапазона",
  "The date is out of range": "Такой даты не бывает",
  "expectedVersion is required": "Нужна версия задачи: обновите экран и повторите",
  "Message body required": "Введите текст сообщения",
  "Message body must be text": "Текст сообщения должен быть строкой",
  "Message body is too long": "Сообщение слишком длинное",
  "Unsupported message kind": "Такой вид сообщения не поддерживается",
  "That message kind is written by the server, not by a client": "Такой вид сообщения создаёт только сервер",
  "Only the author may edit this message": "Править сообщение может только его автор",
  "A thread cannot start inside another thread": "Ветку нельзя начать внутри другой ветки",
  "No conversation preference supplied": "Не указано, что менять",
  "A guest joins only where they were invited": "Гость входит только туда, куда его позвали",
  "Guests have no commitments": "У гостей нет обязательств",
  "You may only edit your own profile": "Править можно только свою карточку",
  "Nothing to update": "Нечего менять",
  "Nothing to change": "Нечего менять",
  "A reminder can only be reopened, completed or cancelled": "Напоминание можно только вернуть в ожидание, отметить сделанным или отменить",
  "A reminder title is at most 200 characters": "Название напоминания — не длиннее 200 символов",
  "Reminder not found": "Напоминание не найдено",
  "Note not found": "Заметка не найдена",
  "Highlight not found": "Выделение не найдено",
  "Endpoint not found": "Подписка не найдена",
  "Event not found": "Встреча не найдена",
  "You are not invited to this event": "Вас не приглашали на эту встречу",
  "That person is not invited": "Этого человека не приглашали",
  "Answer must be accepted, tentative or declined": "Ответ — «приду», «под вопросом» или «не приду»",
  "Unknown label kind": "Неизвестный вид метки",
  "Unknown note kind": "Неизвестный вид заметки",
  "Unknown favourite type": "Неизвестный вид избранного",
  "A note needs text": "Заметке нужен текст",
  "A note is at most 2000 characters": "Заметка — не длиннее 2000 символов",
  "A highlight needs the text it covers": "Выделению нужен текст, который оно покрывает",
  "A highlight needs a valid range": "Выделению нужен корректный диапазон",
  "Invalid report range": "Некорректный период отчёта",
  "Report range starts after it ends": "Период отчёта начинается позже, чем заканчивается",
  "Meeting not found": "Встреча не найдена",
  "Meeting processing job not found": "Задача обработки встречи не найдена",
  "Meeting proposal not found": "Предложение по встрече не найдено",
  "Pending meeting proposal not found": "Ожидающее предложение по встрече не найдено",
  "Retry reason is required": "Укажите причину повтора",
  "Cancel reason is required": "Укажите причину отмены",
  "Provider and model are required": "Нужны провайдер и модель",
  "Currency must be a three-letter ISO-style code": "Валюта — трёхбуквенный код",
  "CHAT_ASSISTANT_PROVIDER is not configured": "Помощник по переписке на этом сервере не подключён",
  "LiveKit webhook verification is not configured": "Приём событий звонков на этом сервере не настроен",
  "Realtime media provider is not configured": "Звонки на этом сервере пока не подключены"
}));

const STATUS_RU = { inbox: 'входящая', clarify: 'на уточнении', proposed: 'ожидает принятия', accepted: 'принята', scheduled: 'запланирована',
  in_progress: 'в работе', blocked: 'заблокирована', in_review: 'на проверке', accepted_result: 'результат принят', closed: 'закрыта',
  deferred: 'отложена', cancelled: 'отменена', rejected: 'отклонена' };
export const russianMessage = (message) => {
  const known = RU.get(message);
  if (known) return known;
  // «proposed -> done is not allowed»: внутренние имена состояний человеку ничего не говорят.
  const step = /^(\w+) -> (\w+) is not allowed$/.exec(String(message));
  if (step) return `Из состояния «${STATUS_RU[step[1]] ?? step[1]}» нельзя перейти в «${STATUS_RU[step[2]] ?? step[2]}»`;
  return message;
};
